export const projects = [
  {
    id: "bfa",
    slug: "bfa-business-capital",
    title: "BFA Business Capital",
    category: "Business Website / Financial Services / Web Development",
    filters: ["Business Websites"],
    featured: true,
    tagline: "Modern business funding platform with streamlined online applications",
    description:
      "Modern business funding platform designed to present financing solutions, guide business owners through funding options, and provide streamlined online application experiences.",
    features: [
      "Funding product pages for SBA Loans, Lines of Credit, Term Loans, MCA & Bridge Loans",
      "Online application flow with a dedicated Quick App form",
      "Loan amount selector and business-focused information architecture",
      "Responsive design across desktop and mobile",
      "Funding guides, FAQs and success stories for prospective clients",
    ],
    tech: ["WordPress", "Elementor"],
    github: null,
    live: "https://bfa.business/",
    frame: "browser",
    accent: "#0E8A7A",
  },
  {
    id: "grandpearl",
    slug: "grand-pearl-marquee",
    title: "Grand Pearl Marquee",
    category: "Business Website / Event Venue",
    filters: ["Business Websites"],
    featured: true,
    tagline: "Professional website for a luxury wedding & event venue",
    description:
      "Professional business website for an event and wedding venue, focused on presenting the venue, services, and customer-facing information through a polished digital experience.",
    features: [
      "Live website for a luxury wedding & event venue in Rawalpindi",
      "Premium venue and brand presentation",
      "Modern React single-page application (Vite)",
    ],
    tech: ["React", "Vite", "JavaScript"],
    github: null,
    live: "https://www.grandpearlmarquee.com/",
    frame: "browser",
    accent: "#C08552",
  },
  {
    id: "toheed",
    slug: "toheed-watch-store",
    title: "Toheed Watch Store",
    category: "WordPress / E-Commerce / Business Website",
    filters: ["WordPress", "Business Websites"],
    featured: true,
    tagline: "Real-world e-commerce store for a watch retail business",
    description:
      "Real-world WordPress e-commerce website built for a watch retail business — a live storefront with a product catalog across Casio, Citizen, G-Shock and Edifice brands, plus a complete shopping experience with cart and account flows.",
    features: [
      "WordPress + Elementor e-commerce build",
      "WooCommerce product catalog with brand categories",
      "Complete shopping experience — cart, accounts and product pages",
      "Responsive, business-focused design for a live retail store",
    ],
    tech: ["WordPress", "Elementor", "WooCommerce"],
    github: null,
    live: "https://toheedwatches.com/",
    frame: "browser",
    accent: "#FFD166",
  },
  {
    id: "gymflow",
    slug: "gymflow-crm",
    title: "GymFlow CRM",
    category: "Full Stack / SaaS / CRM",
    filters: ["Full Stack", "SaaS"],
    featured: false,
    tagline: "Production-oriented multi-tenant gym management SaaS platform",
    description:
      "A production-oriented SaaS gym management system built with Next.js, Node.js, Express.js, and MongoDB. Multiple gyms independently manage members, staff, membership plans, and attendance, while a Super Admin runs the entire platform from a centralized dashboard.",
    features: [
      "Multi-tenant SaaS architecture with gym-scoped data isolation",
      "Role-Based Access Control (Super Admin, Admin, Receptionist, Trainer)",
      "JWT authentication with bcrypt password hashing",
      "Gym, member, staff, and membership plan management",
      "Platform administration with live statistics",
      "Membership expiry alerts and notifications",
      "Gym-scoped uniqueness via compound MongoDB indexes",
    ],
    tech: ["Next.js", "Node.js", "Express.js", "MongoDB", "JavaScript"],
    github: "https://github.com/abdulkhanmajid01-cmd/GymFlow-CRM",
    live: null,
    frame: "browser",
    accent: "#635BFF",
  },
  {
    id: "gohelper",
    slug: "go-helper",
    title: "GoHelper",
    category: "Full Stack / Mobile / Platform",
    filters: ["Full Stack", "Mobile"],
    featured: false,
    tagline: "On-demand fuel, mechanic assistance & parcel delivery platform",
    description:
      "A multi-interface platform built with Flutter, Firebase, and a Python admin portal. Customers and drivers connect through a real-time ride and service workflow, while an administrator reviews drivers and monitors activity. Features live maps, fare calculation, in-ride chat, and driver approvals.",
    features: [
      "Flutter mobile app for customers and drivers",
      "Google Maps integration and GPS location workflows",
      "Real-time driver matching, tracking and in-ride chat",
      "Python (FastAPI) admin portal for driver approvals",
      "Firebase authentication and Firestore data store",
      "Dynamic fare calculation",
    ],
    tech: ["Flutter", "Dart", "Firebase", "Python", "Google Maps"],
    github: "https://github.com/abdulkhanmajid01-cmd/go-helper",
    live: null,
    frame: "phone",
    accent: "#FF6B6B",
  },
  {
    id: "malis",
    slug: "malis-legal-intelligence-system",
    title: "MALIS — Legal Intelligence System",
    category: "AI / Full Stack",
    filters: ["Full Stack", "AI"],
    featured: false,
    tagline: "AI-powered legal intelligence system (RAG-based)",
    description:
      "An AI-powered legal intelligence system built on a RAG pipeline. Users upload case files and describe incidents, and the system extracts text, builds semantic embeddings, retrieves relevant law references from PPC/PECA, detects cybercrime patterns, and generates structured FIR-style case summaries.",
    features: [
      "RAG pipeline: text extraction, embeddings, FAISS retrieval",
      "NLP with Sentence Transformers (all-MiniLM-L6-v2)",
      "Semantic search over legal documents (PPC & PECA)",
      "Cybercrime pattern detection engine",
      "Automated legal reasoning and case summary drafting",
      "Interactive Gradio application UI",
    ],
    tech: ["Python", "NLP", "RAG", "FAISS", "Sentence Transformers", "Gradio"],
    github:
      "https://github.com/abdulkhanmajid01-cmd/-MALIS---Legal-Intelligence-System",
    live: null,
    frame: "browser",
    accent: "#FF6B6B",
  },
  {
    id: "khangroups",
    slug: "khan-groups-website",
    title: "Khan Groups Website",
    category: "Business Website / Web Development",
    filters: ["Business Websites"],
    featured: false,
    tagline: "Full-stack business website with admin panel",
    description:
      "A full-stack business website built with Next.js, React, Supabase (PostgreSQL), and NextAuth. It includes database-driven blog posts, a working contact form with rate-limiting and email sending, and a login-protected admin panel for managing leads and content.",
    features: [
      "Next.js (App Router) frontend with scroll-reveal animations",
      "Supabase (PostgreSQL) via Prisma ORM",
      "Database-driven blog with ISR",
      "Contact form with validation, honeypot and rate-limiting",
      "NextAuth.js admin authentication and admin panel",
      "Rule-based chatbot widget",
    ],
    tech: ["Next.js", "React", "Supabase", "Prisma", "NextAuth"],
    github: "https://github.com/abdulkhanmajid01-cmd/khan-groups-website",
    live: null,
    frame: "browser",
    accent: "#635BFF",
  },
  {
    id: "voice",
    slug: "voice-assistance",
    title: "Voice Assistance",
    category: "AI / Python",
    filters: ["AI"],
    featured: false,
    tagline: "Python desktop voice assistant with GUI",
    description:
      "A professional Python voice assistant with speech recognition, text-to-speech, web browsing, note-taking, reminders, system controls, and a graphical interface. Built with modular feature files and both voice and interactive command modes.",
    features: [
      "Speech recognition and text-to-speech",
      "Web browsing and Wikipedia searches",
      "Note-taking with save, search and export",
      "Reminders and alarm system",
      "System controls and monitoring",
      "Tkinter-based graphical interface",
    ],
    tech: ["Python", "Speech Recognition", "pyttsx3", "Tkinter"],
    github: "https://github.com/abdulkhanmajid01-cmd/VOICE-ASSISTANCE",
    live: null,
    frame: "browser",
    accent: "#FF6B6B",
  },
];

export const projectFilters = [
  { label: "All", value: "All" },
  { label: "Full Stack", value: "Full Stack" },
  { label: "SaaS", value: "SaaS" },
  { label: "AI", value: "AI" },
  { label: "Mobile", value: "Mobile" },
  { label: "WordPress", value: "WordPress" },
  { label: "Business Websites", value: "Business Websites" },
];